# Generated by Django 4.2.6 on 2023-10-06 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('celebrities', '0004_alter_celebrity_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=350)),
                ('date', models.DateField(auto_now=True)),
                ('likes', models.PositiveIntegerField()),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='celebrities.celebrity')),
            ],
        ),
    ]
