# Generated by Django 4.2.6 on 2023-10-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
