# Generated by Django 4.2.6 on 2023-10-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0002_alter_celebrity_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
