# Generated by Django 4.2.6 on 2023-10-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0003_alter_celebrity_cover_image_alter_celebrity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
