# Generated by Django 4.2.6 on 2023-10-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('garments', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
