# Generated by Django 4.2.6 on 2023-10-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='garment',
            name='garments',
            field=models.ImageField(blank=True, max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='garment',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
