# Generated by Django 4.2.6 on 2023-10-07 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0004_alter_celebrity_name'),
        ('garments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='celebrity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='garments', to='celebrities.celebrity'),
        ),
        migrations.AlterField(
            model_name='garment',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='garment',
            name='garments',
            field=models.ImageField(blank=True, max_length=200, upload_to=''),
        ),
    ]
