# Generated by Django 4.2.6 on 2023-10-06 17:52

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0004_alter_celebrity_name'),
        ('garments', '0002_alter_garment_brand_alter_garment_garments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='celebrity',
            field=models.ForeignKey(default=builtins.id, on_delete=django.db.models.deletion.CASCADE, related_name='garments', to='celebrities.celebrity'),
        ),
        migrations.AlterField(
            model_name='garment',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
