# Generated by Django 4.2.6 on 2023-10-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0004_remove_garment_celebrity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garment',
            name='garments',
        ),
        migrations.AddField(
            model_name='garment',
            name='image',
            field=models.ImageField(blank=True, max_length=200, upload_to=''),
        ),
    ]
