# Generated by Django 4.2.6 on 2023-10-06 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0004_alter_celebrity_name'),
        ('garments', '0004_alter_garment_celebrity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garments', to='celebrities.celebrity'),
        ),
    ]
