# Generated by Django 4.2.6 on 2023-10-08 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0004_alter_celebrity_name'),
        ('garments', '0006_rename_image_garment_garments_garment_celebrity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='celebrity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garments', to='celebrities.celebrity'),
        ),
    ]
