# Generated by Django 4.2.6 on 2023-10-08 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0004_alter_celebrity_name'),
        ('garments', '0007_alter_garment_celebrity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garment',
            name='celebrity_id',
        ),
        migrations.AddField(
            model_name='garment',
            name='celebrity',
            field=models.ForeignKey(db_column='celebrity', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='garments', to='celebrities.celebrity'),
            preserve_default=False,
        ),
    ]
