# Generated by Django 4.2.6 on 2023-10-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0008_remove_garment_celebrity_id_garment_celebrity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garment',
            name='garments',
        ),
        migrations.AddField(
            model_name='garment',
            name='image',
            field=models.ImageField(default=1, max_length=200, upload_to=''),
            preserve_default=False,
        ),
    ]
