# Generated by Django 4.2.6 on 2023-10-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garments', '0009_remove_garment_garments_garment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='image',
            field=models.URLField(),
        ),
    ]
